stages:
  - build
  - test
  - security
  - notify
  - docker

variables:
  PROJECT_NAME: vprofile
  JAVA_OPTS: ${JAVA_OPTIONS} # this variable defined in GitLab UI

# Build Stage
build-job:
  stage: build
  # this image avl in DockerHub, when this stage runs on inbuilt runner, it's going to fetch this image in that runner and create a container from that
  image: maven:3.9.9-eclipse-temurin-17  
  rules:
    # Trigger this job on pushes to main or develop
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "develop"'
    # Trigger on merge requests
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    # Trigger this job when pipeline started manually
    - if: '$CI_PIPELINE_SOURCE == "web"'
    #Trigger this job on scheduled pipelines
    - if '$CI_PIPELINE_SOURCE == "schedule"''
    #otherwise never run this job, if none of the above conditions match
    - when: never
  #this below script runs on the created container
  script: 
    - echo "Building the project ${PROJECT_NAME}-test"
    - echo "Java Options are ${JAVA_OPTS}"
    # - echo "My Secret is ${MY_SECRET}" #the variable which is defined as marked and hidden in GitLab UI (Secret) output will shown as [MASKED]
    # - echo "The source of the pipeline trigger is $CI_PIPELINE_SOURCE for branch $CI_COMMIT_BRANCH" # these 2 variables are pre-defined vars aval in GitLab output ex: push, main
    - mvn install
  after_script:
    - ls -la 
  #to store the artifacts
  artifacts:
    paths:
      - target/*.war
    when: always
    
#Test Stage
test-job:
  stage: test
  image: maven:3.9.9-eclipse-temurin-17 
  needs: [build-job] # to run the test job after the build job, normally also it will run in same manner, but here I want to run code scanning job and test job parallelly after running build job
  only: # to make this stage run only on the main branch (old way of doing, can use rules which used in previous job)
    - main 
  script: 
    - echo "Running Unit Tests in the project ${PROJECT_NAME}-test"
    - mvn test
    - mvn checkstyle:checkstyle

security-scan:
  stage: security
  image:
    name: aquasec/trivy:latest
    entrypoint: [""] # to nullify the first command else commands in script takes as trivy trivy [options]
  needs: [build-job]
  script:
    # kept exit code 0, so even finds any vulnerabilty still job will pass. But if we give exit code 1 then incase of high severity vulnerabilities job will fail if we give --severity HIGH
    - trivy fs --format json --exit-code 0 --vuln-type os,library --output trivy-results.json . 
  after_script:
    - ls -la 
  # to store the artifacts
  artifacts:
    paths:
      - trivy-results.json
    when: always

docker-build-publish:
  stage: docker
  image: docker:latest #this image just provides docker cli but not deamon
  services:
    - docker:dind #this is one more container acts as deamon (for security reason in GitLab, creating 2 containers here)
  needs: [security-scan]
  variables:
    DOCKER-TLS-CERTDIR: ""
    IMAGE_TAG: $CI_COMMIT_SHA
  script:
    - echo "Logging in to GitLab Container Registry..."
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" -- password-stdin $CI_REGISTRY
    - echo "Building Docker image with custom Dockerfile..."
    - docker build -f Docker-files/app/multistage/Dockerfile -t $CI_REGISTRY_IMAGE:$IMAGE_TAG .
    - docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG

# notify on failure job (can even setup slack notification etc)
notify-on-failure:
  stage: notify
  script:
    - echo "Build or Test job failed for ${PROJECT_NAME}! please check logs."
  when: on_failure # to make this job runs only if any previous job fails


