name: Build Job #name of the workflow

on: 
  push:
    branches: 
      - main
      
  pull_request:
    branches:
      - main

  workflow_dispatch:

  # schedule:
  #   - cron: "10 14 * * 1-5" #run at 2:10PM from monday to friday

# to make this workflow file have permission read-only from this repo 
permissions:
  contents: read

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 #we can pass input parameters to actions using with, we can refer https://github.com/marketplace/actions/checkout 

      - name: Maven Build
        run: mvn install #it creates an artifact, generally everything will get deleted once workflow completes. so saving using below actions

      - name: Upload Build Artifact (WAR)
        uses: actions/upload-artifact@v4
        with:
          name: vprofile-app #name of the artifact we want, will create a zip of our artifact
          path: target/*.war

       # Using conditions
      - name: Notify if Build Fails
        if : failure() #predefined function, checks if previous steps failed. We have other functions such as success(), always() etc
        run: echo "Build Job failed! Please check logs."


  Testing:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0        

      - name: Run tests on main branch
        if: github.ref == '/refs/heads/main' # run the below run command only if the branch is main. github.ref is a github context variable holds the value of branch using which workflow is running
        run: mvn test

      - name: Checkstyle
        if: github.ref == '/refs/heads/main'
        run: mvn checkstyle:checkstyle

      - name: Run tests on other branches
        if: github.ref != '/refs/heads/main'
        run: echo "Skipping unit tests and code analysis"

  Security_Scan:
    runs-on: ubuntu-latest
    needs: Build  #so once build job completes, Testing and securit_scan job both runs parallelly
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   

      - name: Run Trivy filesystem scan # Security scanning
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: fs # other scan types such as image, fs, repo etc
          scan-ref: . # means scan current directory
          format: json # format of output i want
          exit-code: 0 # exit code 0 means continue with next step even if vulnerabilities found
          vuln-type: os,library
          output: trivy-results.json

      - name: UploadTrivy scan results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-results #name of the artifact we want
          path: trivy-results.json
